language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - if [ $TRAVIS_RUST_VERSION == "stable" ]; then cargo fmt --all --verbose -- --check; fi
  - cargo build --verbose --workspace
  - cargo test --verbose --workspace
